2020-09-16 10:52:46 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2020-09-16 10:52:46 INFO     rasa_sdk.executor  - Registered function for 'action_Perform_action'.
2020-09-16 10:52:46 INFO     rasa_sdk.executor  - Registered function for 'action_Search_order'.
2020-09-16 10:52:46 INFO     rasa_sdk.executor  - Registered function for 'action_search_product'.
2020-09-16 10:52:46 INFO     rasa_sdk.executor  - Registered function for 'action_Look_for_customer_file'.
2020-09-16 10:52:46 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://localhost:5055
Unable to start server
Traceback (most recent call last):
  File "/home/tf/anaconda3/lib/python3.7/site-packages/sanic/server.py", line 895, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1727, in create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5055): address already in use
